fig, ax = plt.subplots()
stations["bike_stands"].plot.hist(ax=ax, alpha=.5, label="Total bike stands")
stations["available_bikes"].plot.hist(ax=ax, alpha=.5, label="Available bikes")
ax.legend()
ax.grid()